# Generated by Django 5.2.6 on 2025-10-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Voluntree', max_length=100)),
                ('site_tagline', models.CharField(blank=True, max_length=200)),
                ('site_description', models.TextField(blank=True)),
                ('admin_email', models.EmailField(max_length=254)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('noreply_email', models.EmailField(blank=True, max_length=254)),
                ('send_welcome_email', models.BooleanField(default=True)),
                ('send_approval_emails', models.BooleanField(default=True)),
                ('send_event_reminders', models.BooleanField(default=True)),
                ('require_event_approval', models.BooleanField(default=False)),
                ('max_event_duration', models.IntegerField(default=30, help_text='Maximum event duration in days')),
                ('min_volunteers_per_event', models.IntegerField(default=1)),
                ('max_volunteers_per_event', models.IntegerField(default=100)),
                ('event_cancellation_hours', models.IntegerField(default=24, help_text='Minimum hours notice for cancellation')),
                ('auto_complete_events', models.BooleanField(default=True)),
                ('allow_volunteer_registration', models.BooleanField(default=True)),
                ('allow_ngo_registration', models.BooleanField(default=True)),
                ('require_email_verification', models.BooleanField(default=False)),
                ('min_volunteer_age', models.IntegerField(default=13)),
                ('require_ngo_verification', models.BooleanField(default=True)),
                ('auto_approve_verified_ngos', models.BooleanField(default=False)),
                ('ngo_approval_time', models.IntegerField(default=3, help_text='Review time in days')),
                ('enable_push_notifications', models.BooleanField(default=False)),
                ('enable_sms_notifications', models.BooleanField(default=False)),
                ('notify_on_new_event', models.BooleanField(default=True)),
                ('notify_on_event_update', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(default='We are currently performing maintenance. Please check back soon.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
